name = "lean_runner"
defaultTargets = ["lean_runner"]

[[lean_exe]]
name = "lean_runner"
root = "Main"
buildType = "relWithDebInfo"

[[require]]
name = "Regex"
git = "https://github.com/pandaman64/lean-regex"
rev = "53fe74eb21ad2fae2588dca1f2ecffb88a096c4b"
subDir = "regex"
