name = "lean_runner"
defaultTargets = ["lean_runner"]

[[lean_exe]]
name = "lean_runner"
root = "Main"
buildType = "relWithDebInfo"

[[require]]
name = "Regex"
git = "https://github.com/pandaman64/lean-regex"
rev = "e1600a18d170eab0a079d6f96c79abdb23e80828"
subDir = "regex"
