name = "lean_runner"
defaultTargets = ["lean_runner"]

[[lean_exe]]
name = "lean_runner"
root = "Main"
buildType = "relWithDebInfo"

[[require]]
name = "Regex"
git = "https://github.com/pandaman64/lean-regex"
rev = "a3199cdd0a46996bb1897e7d83022cd0f54804eb"
subDir = "regex"
